### ISSUE TITLE
web service error

### ISSUE THREAD

**Issue by noraj** [reconmap/reconmap#105]
Even with the [web service whitelisted in CORS](https://github.com/reconmap/reconmap/pull/104) the WS fails after a dozens of seconds.

![image](https://user-images.githubusercontent.com/16578570/160282396-4093e090-0fae-4521-9483-ed0276b71328.png)

![image](https://user-images.githubusercontent.com/16578570/160282415-d34ca0b5-bb5f-4604-8e3d-7d043290e476.png)

**Comment by santiagolizardo** [comment]
I believe this no longer is an issue. Will confirm shortly. Thanks
