### ISSUE TITLE
Project Can't be add More then Five.

### ISSUE THREAD

**Issue by Arpan5555** [reconmap/reconmap#106]
Whenever I create Project At that time Project not add on reconmap using Normal And Admin Users.

**Comment by Arpan5555** [comment]
Also One more thing Notification like "Project Created (Actions Completed)" Message Shows But I Can't Show it on projects.
![reconmap issue](https://user-images.githubusercontent.com/104006934/164006228-509af530-dfce-4eda-9601-94869c3b04ef.png)

**Comment by santiagolizardo** [comment]
Hi @Arpan5555 ; Thanks for reporting this issue. I made an improvement to stay in the project creation form if there is a problem with the data entered. I suspect in your case is a duplicated project name. Let me know if the updates fix your problem. Ta

https://github.com/reconmap/web-client/commit/aff5a3505dd201642566f96b9fd901b79c602547
https://github.com/reconmap/rest-api/commit/107f6f7ef99d61186462e19514317928b60566ea

**Comment by Arpan5555** [comment]
Thank you @santiagolizardo it was very helpful to know Some new thing in Reconmap.

**Comment by Arpan5555** [comment]
hey @santiagolizardo Again I am Entering 20 Projects that won't create Any Other Projects.

**Comment by Arpan5555** [comment]
Error Resolved, Thanks
