### ISSUE TITLE
Default credentials not working

### ISSUE THREAD

**Issue by chosenonehacks** [reconmap/reconmap#110]
I have followed installation instructions on: https://docs.reconmap.com/admin-manual/debian-nginx-letsencrypt.html

I have started the instance and can access it on my domain, however, when trying to log in using default credentials I cannot log in. 
https://docs.reconmap.com/admin-manual/default-credentials.html

The error after posting credentials is: Failed to fetch

What could be wrong?

**Comment by moayadalmalat** [comment]
Try one of this browser version: https://docs.reconmap.com/user-manual/browser-requirements.html
