### ISSUE TITLE
ERROR: The Compose file './docker-compose.yml' is invalid because:

### ISSUE THREAD

**Issue by moayadalmalat** [reconmap/reconmap#112]
Hi,

I try to build reconmap on a VM... when I do docker-compose up -d or sudo docker-compose up -d it's return the following error:
```
root@docker ~/reconmap# docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'mysql'
root@docker ~/reconmap# sudo docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'api'
```

I'm not sure where is the issue, since I don't have a big experience with dockers, should I do a specific step before I do docker-compose up -d?

If you need more information, let me know.

Thank you in advance.

**Comment by santiagz** [comment]
install latest docker-compose version 

My verion: `Docker Compose version v2.7.0`

Works for me:
```
sudo curl -L "https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
```
```
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by moayadalmalat** [comment]
Thank you, @santiagz  I'll try your way in a few hours and let you know!

**Comment by moayadalmalat** [comment]
fixed! Thank you :)
