### ISSUE TITLE
Add support for multiple languages in the UI

### ISSUE THREAD

**Issue by santiagolizardo** [reconmap/reconmap#113]
Add support for multiple languages to the web client

**Comment by psyray** [comment]
@santiagolizardo 
I could translate in french if you want.

**Comment by santiagolizardo** [comment]
That would be great @psyray . There is _some_ info on how to translate the UI here: https://docs.reconmap.com/development/translations.html
Let me know if you need any help with that. I can create the empty French files if you wish. Thanks!

**Comment by psyray** [comment]
I want to start the translation but it seems there isn't so much strings to translate, is it normal ?

**Comment by santiagolizardo** [comment]
Most strings have now been translated. (https://github.com/reconmap/web-client/blob/master/packages/app/src/translations/fr/application.json) Thanks anyway, @psyray !
