### ISSUE TITLE
Updating template task does not list the template project

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#114]
Hi,

When I try to update template task, the template is not listed in the project combo box
Only the real project is listed, so when the task is saved it moves in the listed project.

Step to reproduce (on demo of reconmap)
- Go to a **project template** and click sur **Task** tab, then click **Edit Button**
![image](https://user-images.githubusercontent.com/1230954/186872745-a5e91187-cd09-4de0-b515-fd716a9157bd.png)
- On the edit page template project is not selected
![image](https://user-images.githubusercontent.com/1230954/186873043-d5da9bab-a617-4171-8726-3f8c64443833.png)
- Not even listed
![image](https://user-images.githubusercontent.com/1230954/186873382-8172aab3-661c-4a25-aa21-d3c0f4636c01.png)

You should permit to list the template projects (Maybe like this : **[Template] CAIRNINDIA** to quickly identify) in the combo box

**Comment by santiagolizardo** [comment]
Thanks for reporting this issue @psyray . This should now be resolved.

**Comment by psyray** [comment]
@santiagolizardo Does not seem to work in the current release, do you push modification to the latest docker image ?
Tested in the demo, does not work also

**Comment by psyray** [comment]
Docker updated, checked and resolved.
Thanks ;)
