### ISSUE TITLE
Add the possibility to clone tasks from template to an existing project after initial cloning

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#115]
Currently, If we add a new task in a template project (to integrate in a future project), we can't copy this task to add it in an existing project.
We need to enter this task again.

it could be very useful to add an action, in the task list, to clone task into an existing project (real or template).
This prevent to enter the new task twice and help organize the project

**Comment by santiagolizardo** [comment]
Hi @psyray ; I just added the option to clone tasks from projects or templates. Once a task is cloned you can assign it to another project or template irrespectively. Hope that helps!

**Comment by psyray** [comment]
All good, validated.
Thanks for your work !
