### ISSUE TITLE
Authentican error: Timeout when waiting for 3rd party check iframe message",

### ISSUE THREAD

**Issue by mach1982** [reconmap/reconmap#119]
when launching reconmap using docker I get  the error " Authentican error: Timeout when waiting for 3rd party check iframe message", from google I think it has  something to do with keycloak module

**Comment by chssn** [comment]
I'm also seeing this issue - have posted steps and things under #116 here - https://github.com/reconmap/reconmap/issues/116#issuecomment-1282175211

**Comment by ttyx0** [comment]
Hi, I am facing the same issue. Tried all comments and config changes provided in https://github.com/reconmap/reconmap/issues/116 but still no lack. I will make clean install in a clean VM later again to test, just in case i missed something.
