### ISSUE TITLE
Visibility combo box not aligned

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#122]
Little UI bug
On the vulnerability form the combo box **Visibility** is not aligned
![image](https://user-images.githubusercontent.com/1230954/194911560-6fae36fb-58ac-435a-94d7-8ff867fe7fe9.png)

**Comment by santiagolizardo** [comment]
Sorted, thanks for reporting this issue

![image](https://user-images.githubusercontent.com/220190/195399774-6adea343-19e5-472d-b206-4fc99da74819.png)
