### ISSUE TITLE
User deletion prevented by audit log databse table

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#124]
When you delete a user if the user has already logged in you can't delete it because a key constraint prevent the user to be deleted.

Error message
```
Operation failed: There was an error while applying the SQL script to the database.
Executing:
DELETE FROM `reconmap`.`user` WHERE (`id` = '17');

ERROR 1451: 1451: Cannot delete or update a parent row: a foreign key constraint fails (`reconmap`.`audit_log`, CONSTRAINT `audit_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`))
SQL Statement:
DELETE FROM `reconmap`.`user` WHERE (`id` = '17')
```
Here's the line that prevent deletion
![image](https://user-images.githubusercontent.com/1230954/196785229-251320da-aa07-4cde-a7d1-43ba60f31223.png)

I think you should do a CASCADE delete
Currently you have a RESTRICT rule in the database
![image](https://user-images.githubusercontent.com/1230954/196785417-d50bd069-0c61-4dc3-a0ed-e0430649dd6c.png)

Or If you do not want to delete the audit log, you can set a SET NULL rule (but this is a non sense)

And you should manage the API return because it deletes it from keycloak, don't delete it from reconmap and return a successful delete message, which is partially right

**Comment by psyray** [comment]
And, in general, I think you should review all the foreign key constraints and set it accordingly to prevent the key constraint error while updating or deleting entities

**Comment by santiagolizardo** [comment]
Thanks for reporting this problem @psyray . I agree this needs to be changed but I don't like the idea of removing the user id or the audit trail as that exactly what a rogue user would do to clear their tracks.
I am thinking of adding a user name column to the audit table and storing both user id and username. When a user is deleted the user id is set to null but the username stays in place. Although this will take more storage at least it would allow to go back in time and see who did what (based on user name and user id, if available)
Thoughts?

**Comment by psyray** [comment]
👍
Good idea, easy to implement

**Comment by santiagolizardo** [comment]
In the end I had to resolve this in a different way by simply adding the `ON DELETE CASCADE` to the foreign key. This is because adding user_name table would require adding one more query before each and every audit call to retrieve the user info from user id.
I guess one way to retain all history even when a user trail is deleted is by backing up the audit log every day or hour using the API and some sort of cron if somebody requires it
Hope this works for you @psyray
