### ISSUE TITLE
Markdown used in remediation does not work

### ISSUE THREAD

**Issue by psyray** [reconmap/reconmap#126]
Markdown is not interpreted

UI
![image](https://user-images.githubusercontent.com/1230954/196792903-2cf7101f-32d0-4c66-9a25-202fb626ce52.png)

Report
![image](https://user-images.githubusercontent.com/1230954/196792783-fffca34d-efda-4ccb-b029-2dbd9ccc808d.png)

**Comment by santiagolizardo** [comment]
This should now be fixed. Thanks for reporting the issue @psyray

**Comment by psyray** [comment]
:+1: All good thanks
