### ISSUE TITLE
User creation doesn't work

### ISSUE THREAD

**Issue by v0lp3** [reconmap/reconmap#128]
In the latest build the user creation doesn't work. I tested in local and on your demo.

![Screenshot from 2022-10-31 16-04-41](https://user-images.githubusercontent.com/20267645/199040758-87abb2e8-ea93-4036-b108-bee26931867c.png)

The last working commit is `d81d45a241863677cd9374bf81eda2a85094b480` in `rest-api`

**Comment by VHAE04** [comment]
yep i try make user it call port 5510 but code 500 ;D

**Comment by santiagolizardo** [comment]
@VHAE04 unfortunately I couldn't reproduce this issue with the latest version of all code and containers. Are you running this from the containers? Have you pulled down the latest versions? Thanks

**Comment by sasaga** [comment]
I have the same error, has anyone found a solution?
