### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by sasaga** [reconmap/reconmap#130]
I am installing the latest version and I have a CORS policy error when accessing the panel, I made the suggested changes in config.json and environment.js but it doesn't seem to have any effect.

<img width="1338" alt="Screenshot 2023-02-17 at 9 16 13 AM" src="https://user-images.githubusercontent.com/8051657/219679930-10bc48ec-6857-49fb-9262-6775847499a6.png">
<img width="1251" alt="Screenshot 2023-02-17 at 9 16 23 AM" src="https://user-images.githubusercontent.com/8051657/219679980-4f5f9c48-f046-4e20-9a90-12141d8b6e9f.png">

**Comment by 2mindz** [comment]
I am having the same issue. How were you able to resolve this?

**Comment by sasaga** [comment]
Honestly I did everything, but try trying to authenticate with the default user admin:admin123 and it seems to load most things, which makes me think it's a permissions issue, but I'm just bluffing, so I don't really know the root problem, now I have problems creating users.

**Comment by 2mindz** [comment]
Ah okay, thank you. I'll keep trying to figure it out.

**Comment by psyray** [comment]
Hi, @sasaga 
Could you put your environment.js and the content of the application.log when this error appears ?
CORS error could be a PHP error

**Comment by 2mindz** [comment]
@psyray  I am having the same exact issue with a set up. It appears I don't have an application.log file within the API container but here is my environment.js file.  Does the application log have to be set up in the container ?I'm not using SSL or hostnames so everything is pointing to localhost.  If this is a PHP-related CORS issue where should I look?

`window.env = {
    REACT_APP_SECURE_TRANSPORT_ENABLED: false,

    // Reconmap API's URL including protocol and port but not trailing slash
    REACT_APP_DEFAULT_API_URL: 'http://localhost:5510',

    // hostname:port for the Reconmap's notifications service
    REACT_APP_NOTIFICATIONS_SERVICE_HOST_PORT: 'localhost:5520',

    // hostname:port for the Reconmap's agent service
    REACT_APP_AGENT_SERVICE_HOST_PORT: 'localhost:5520',

    // Web application context path e.g. / (for http://127.0.0.1:5500) or /reconmap (for http://127.0.0.1:5500/reconmap)
    // REACT_APP_CONTEXT_PATH: '/reconmap',

    REACT_APP_KEYCLOAK_CONFIG: {
        url: 'http://localhost:8080',
        realm: 'reconmap',
        clientId: 'web-client'
    }
};
`

**Comment by psyray** [comment]
> @psyray I am having the same exact issue with a set up. It appears I don't have an application.log file within the API container but here is my environment.js file. Does the application log have to be set up in the container ?

application.log should be outside the container as there is a volume config in the docker-compose.yml file
```yaml
  api:
    container_name: rmap-api
    image: quay.io/reconmap/rest-api:latest
    restart: unless-stopped
    volumes:
      - "./config.json:/var/www/webapp/config.json"
      - "./logs:/var/www/webapp/logs/"
      - "./data:/var/www/webapp/data/"
```
So if the logs is missing, check if the logs dir is correctly created in the same dir as the docker-compose.yml file

Anyway you can watch the log file inside the container by docker exec in it
```
docker exec -it rmap-api /bin/bash
```

> I'm not using SSL or hostnames so everything is pointing to localhost. If this is a PHP-related CORS issue where should I look?
> 
It shouldn't be a problem

**Comment by 2mindz** [comment]
@psyray Thank you for your help so far.  I found that I had a typo in the logging path parameter in config.json. I have corrected that issue and see this in the logs:
```[2023-03-09T17:36:45.288393+00:00] http.WARNING: file_get_contents(http://localhost:8080/realms/reconmap): Failed to open stream: Cannot assign requested address on /var/www/webapp/src/Services/KeycloakService.php:28 [] []
[2023-03-09T17:36:45.289217+00:00] http.ERROR: json_decode(): Argument #1 ($json) must be of type string, bool given [] []
[2023-03-09T17:36:45.293023+00:00] http.WARNING: file_get_contents(http://localhost:8080/realms/reconmap): Failed to open stream: Cannot assign requested address on /var/www/webapp/src/Services/KeycloakService.php:28 [] []
[2023-03-09T17:36:45.293804+00:00] http.ERROR: json_decode(): Argument #1 ($json) must be of type string, bool given [] []
[2023-03-09T17:36:45.304525+00:00] http.WARNING: file_get_contents(http://localhost:8080/realms/reconmap): Failed to open stream: Cannot assign requested address on /var/www/webapp/src/Services/KeycloakService.php:28 [] []
[2023-03-09T17:36:45.305582+00:00] http.ERROR: json_decode(): Argument #1 ($json) must be of type string, bool given [] []
[2023-03-09T17:36:45.309871+00:00] http.WARNING: file_get_contents(http://localhost:8080/realms/reconmap): Failed to open stream: Cannot assign requested address on /var/www/webapp/src/Services/KeycloakService.php:28 [] []
[2023-03-09T17:36:45.310976+00:00] http.ERROR: json_decode(): Argument #1 ($json) must be of type string, bool given [] []
[2023-03-09T17:36:45.311468+00:00] http.WARNING: file_get_contents(http://localhost:8080/realms/reconmap): Failed to open stream: Cannot assign requested address on /var/www/webapp/src/Services/KeycloakService.php:28 [] []
[2023-03-09T17:36:45.312349+00:00] http.ERROR: json_decode(): Argument #1 ($json) must be of type string, bool given [] []
```
I guess now I need to figure out why I am get this error and where to fix  it.

**Comment by why-always-me-mta** [comment]
> > @psyray I am having the same exact issue with a set up. It appears I don't have an application.log file within the API container but here is my environment.js file. Does the application log have to be set up in the container ?
> 
> application.log should be outside the container as there is a volume config in the docker-compose.yml file
> 
> ```yaml
>   api:
>     container_name: rmap-api
>     image: quay.io/reconmap/rest-api:latest
>     restart: unless-stopped
>     volumes:
>       - "./config.json:/var/www/webapp/config.json"
>       - "./logs:/var/www/webapp/logs/"
>       - "./data:/var/www/webapp/data/"
> ```
> 
> So if the logs dir is missing, check if the logs dir is correctly created, with the good permissions in the same dir as the docker-compose.yml file
> 
> Anyway you can watch the log file inside the container by docker exec in it
> 
> ```
> docker exec -it rmap-api /bin/bash
> ```
> 
> > I'm not using SSL or hostnames so everything is pointing to localhost. If this is a PHP-related CORS issue where should I look?
> 
> It shouldn't be a problem
> 
> And your config seems to be good

can you show me my docker-compose.yml,please

**Comment by psyray** [comment]
> 

Look here
https://github.com/reconmap/reconmap/issues/116#issuecomment-1256936183
