### ISSUE TITLE
No static file found in the "rmap-web-client"docker.

### ISSUE THREAD

**Issue by scanner521** [reconmap/reconmap#135]
In the latest docker update, after I changed the ip address for installation, there seems to be an error in the request method.
![image](https://github.com/reconmap/reconmap/assets/113080554/86ac14cb-d481-45af-a03a-0ed0c9b9f73b)

-----------------------------------------------------------------
When I checked this problem, I found that the page went to find a file that I don't know where, but I couldn't find it. Could you please help me look at it?
![image](https://github.com/reconmap/reconmap/assets/113080554/88ad56b0-ffd6-49b1-af68-37e296a67d32)

**Comment by scanner521** [comment]
In my search for the error, I found that no logs were generated in the "logs" directory, and in the "rmap-api" directory, "/usr/log/nginx/", both files were empty, leaving me with no way to proceed.
![1691477010854](https://github.com/reconmap/reconmap/assets/113080554/cf43b2f5-54b2-453c-a2d5-5643e018719f)
![1691477085054](https://github.com/reconmap/reconmap/assets/113080554/08b8bf47-fdf2-419b-b804-590846e728b6)

**Comment by santiagolizardo** [comment]
Hi @scanner521 ; Apologies for the inconvenience. You probably need to update your `environment.js file to look like this one: https://github.com/reconmap/reconmap/blob/master/environment.js

All the variables with prefix `REACT_APP_` were renamed to `VITE_`.

Let me know if that helps. Thanks

**Comment by scanner521** [comment]
> 你好@scanner521; 不便之处敬请原谅。您可能需要更新您的“environment.js”文件，使其看起来像这样：https://github.com/reconmap/reconmap/blob/master/environment.js
> 
> 所有带有前缀的变量都`REACT_APP_`被重命名为`VITE_`.
> 
> 让我知道这是否有帮助。谢谢

Thank you very much, this is a perfect solution to any problem.

> 你好@scanner521; 不便之处敬请原谅。您可能需要更新您的“environment.js”文件，使其看起来像这样：https://github.com/reconmap/reconmap/blob/master/environment.js
> 
> 所有带有前缀的变量都`REACT_APP_`被重命名为`VITE_`.
> 
> 让我知道这是否有帮助。谢谢

Thank you very much, this is a perfect solution to any problem.
