### ISSUE TITLE
Reconmap won't render or create users

### ISSUE THREAD

**Issue by oerlex** [reconmap/reconmap#136]
I have a fresh install of reconmap and can successfully login. The application won't render correctly. I also get a 405 error when interacting with the DB. There are no logs in the main log directory.

Any ideas? Maybe PsyRay can help ❤️

**Comment by santiagolizardo** [comment]
This is probably caused by this same issue: https://github.com/reconmap/reconmap/issues/135#issuecomment-1675413879
All you need to do is rename the variables from `REACT_APP_` to `VITE_`. Hope that helps
