### ISSUE TITLE
Subdomain takeover on the demo

### ISSUE THREAD

**Issue by cyb3rjerry** [reconmap/reconmap#138]
Hey folks, looks like someone accidentally took over the demo subdomain lol

![image](https://github.com/reconmap/reconmap/assets/92945113/dc1fb38d-b6d4-4510-9a83-2397c2ea3070)

On https://demo.reconmap.com/

**Comment by cyb3rjerry** [comment]
Wontfix for inactivity is wild lol

**Comment by santiagolizardo** [comment]
Thanks for reporting this @cyb3rjerry . The issue has now been solved.
