### ISSUE TITLE
installation is breaking up (container rmap-mysql is unhealthy)

### ISSUE THREAD

**Issue by littlAcen** [reconmap/reconmap#140]
[root@my-vps reconmap]# /usr/libexec/docker/cli-plugins/docker-compose up
[+] Running 5/0
 ✔ Container rmap-mysql       Running                                                                                                                                                        0.0s 
 ✔ Container rmap-web-client  Running                                                                                                                                                        0.0s 
 ✔ Container rmap-api         Running                                                                                                                                                        0.0s 
 ✔ Container rmap-agent       Running                                                                                                                                                        0.0s 
 ✔ Container rmap-redis       Running                                                                                                                                                        0.0s 
Attaching to keycloak-1, rmap-agent, rmap-api, rmap-mysql, rmap-redis, rmap-web-client
rmap-mysql       | 2024-08-12 20:44:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.0-1.el9 started.
rmap-agent       | time="2024-08-12T20:44:37Z" level=debug msg="searching for notifications..."
rmap-mysql       | 2024-08-12 20:44:37+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
rmap-mysql       | 2024-08-12 20:44:37+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.4.0-1.el9 started.
rmap-mysql       | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
rmap-agent       | time="2024-08-12T20:44:41Z" level=debug msg="searching for notifications..."
rmap-mysql exited with code 137
dependency failed to start: container rmap-mysql is unhealthy

**Comment by santiagolizardo** [comment]
Hi @littlAcen ; I was unable to reproduce the issue . Could you let me know more about your setup/environment? Thanks
