### ISSUE TITLE
edit profile not loading

### ISSUE THREAD

**Issue by MuhammadNaeem42** [reconmap/reconmap#143]
![Screenshot from 2024-09-28 08-49-14](https://github.com/user-attachments/assets/13366230-f7f1-4d40-9c59-4744a4059bee)

**Comment by santiagolizardo** [comment]
Hi @MuhammadNaeem42 ; Could you pull the latest version and check again please? This should no longer be an issue. Thanks

**Comment by santiagolizardo** [comment]
Closing as I was unable to reproduce it. Thanks
