### ISSUE TITLE
Private Projects with Member-Only View and Edit

### ISSUE THREAD

**Issue by oerlex** [reconmap/reconmap#37]
Hi! Great tool that me and some folks would love using. We require though that only users that are assigned to projects can see and edit any project related details. The project overview page should be limited to members that have been invited by the creator of the project.

**Comment by santiagolizardo** [comment]
Hi @oerlex ; I finally managed to complete a first iteration of this. I have introduced the concept of project visibility. Public projects can be seen by anyone, whereas private ones can only be seen by their members (and admins). This is combination with user roles allows you to have people on projects that can only view/modify their properties.
Closing this for now but please open other issues if you have other requests. Thanks!
