### ISSUE TITLE
Question about alternate login mechanisms

### ISSUE THREAD

**Issue by bplaxco** [reconmap/reconmap#42]
Question, is there any way to set up an OIDC or SAML login flow with Reconmap? Or maybe integrate it with https://oauth2-proxy.github.io/oauth2-proxy/?

I poked around the docs and code a bit but I may have missed it.

**Comment by bplaxco** [comment]
@santiagolizardo cool, thanks! Out of the two (OIDC vs SAML) OIDC would be the preferred (plus I've found that one easy to implement by from scratch if not going the oauth2-proxy route).

**Comment by bplaxco** [comment]
@santiagolizardo is there anything that needs to be done with this request (given the plan to add it to the roadmap), or is it alright if stalebot closes it out?

**Comment by santiagolizardo** [comment]
Don't worry @bplaxco . I just added the label `pinned` which causes stale bot not to close it. The bot integration was added Yesterday and the initial configuration was a bit too aggressive :)

**Comment by bplaxco** [comment]
Cool cool, thanks for confirming ^_^

**Comment by santiagolizardo** [comment]
Hi @bplaxco ; Closing this ticket as integration with Keycloak is now completed. (see https://dev.to/reconmap/reconmap-200-release-notes-45o8) Thanks!
