### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by 00xData** [reconmap/reconmap#43]
Hello i recently install this tool in a docker, but when i try to login i get this error.

NetworkError when attempting to fetch resource. 

Did i need to reinstall the API?

Thanks!

**Comment by santiagolizardo** [comment]
Hi @00xData ; If you are running the tool using docker-compose then there should be a `logs/application.log` file available with some information about errors. Otherwise look at the network tab in your browser for any clues. Let me know if I can be of any help to you
