### ISSUE TITLE
"Network Error" on Creating Reports / Downloading Reports

### ISSUE THREAD

**Issue by fumamatar** [reconmap/reconmap#46]
Hi Santiago,

I have set up reconmap on my localhost using the docker-compose file, created a client, project, tasks and an example vulnerability.
When creating a new report version, I get the CORS error below, and the notification that there might be missing API connectivity. Still, after refreshing the page, the report version is created.

![image](https://user-images.githubusercontent.com/51821028/128993951-cc8630e7-4184-4892-8568-a5d4353c1053.png)

Same happens when trying to download the report:

![image](https://user-images.githubusercontent.com/51821028/128994365-593c7764-fc74-42b2-a7a8-92f4dc341233.png)

However, the preview renders just fine. 

The only output I get from docker is this
```
rmap-wss      | server > Frame(fin=True, opcode=9, data=b'T\x85\x8e\xce', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - event = data_received(<10 bytes>)
rmap-wss      | server < Frame(fin=True, opcode=10, data=b'T\x85\x8e\xce', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - received solicited pong: 54858ece
rmap-wss      | server > Frame(fin=True, opcode=9, data=b'\t\xee\x80\xf1', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - event = data_received(<10 bytes>)
rmap-wss      | server < Frame(fin=True, opcode=10, data=b'\t\xee\x80\xf1', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - received solicited pong: 09ee80f1
rmap-wss      | server > Frame(fin=True, opcode=9, data=b'Q\xe2I\xa2', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - event = data_received(<10 bytes>)
rmap-wss      | server < Frame(fin=True, opcode=10, data=b'Q\xe2I\xa2', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - received solicited pong: 51e249a2
rmap-wss      | server > Frame(fin=True, opcode=9, data=b'\xd8\x02-E', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - event = data_received(<10 bytes>)
rmap-wss      | server < Frame(fin=True, opcode=10, data=b'\xd8\x02-E', rsv1=False, rsv2=False, rsv3=False)
rmap-wss      | server - received solicited pong: d8022d45
```

Any idea what went wrong?

**Comment by santiagolizardo** [comment]
Hi @fumamatar . Thanks for reporting the issue. I couldn't reproduce this on any other environment. Could you have a look at the `logs/application.log` file? Have you changed the `config.json` file or is the default one?
I'll have another look and report any findings here.
Thanks

**Comment by fumamatar** [comment]
No, I did not change the config.json. Also, the `application.log` does not exist for me.

If it matters, I am running from inside a Kali VM since Docker for WSL had issues with the docker-compose file.

**Comment by fumamatar** [comment]
I think the issue, at least to the report not being generated lies in the construction of the download URL, as the URL that is called is `http://localhost:8080/attachments/null`.

**Comment by stefan-matz-ITGAIN** [comment]
I think the same happend to me. Create an directory "attachments" inside the data directory. For testing I set the permisson to 777 on both directorys but I am not sure if its necessary.
