### ISSUE TITLE
Add Pagination or lazy load

### ISSUE THREAD

**Issue by 0xcrypto** [reconmap/reconmap#47]
**Is your feature request related to a problem? Please describe.**
I am not sure if this is the right place to open the issue. But we are working on a project that has a big scope and we want to add all the hosts as target in reconmap. `http://localhost:8080/targets?projectId=2` REST endpoint gives a list of all targets in the project which becomes too large for webbrowser to read and page starts hanging.

**Describe the solution you'd like**
Add pagination.

**Describe alternatives you've considered**
Lazy load is another way of doing it but still you will need to have pagination on the api.

**Additional context**
![image](https://user-images.githubusercontent.com/6683856/128975111-e7bc49ef-271b-4254-bb71-7fea0bef3be4.png)

**Comment by santiagolizardo** [comment]
Thanks for reporting this @0xcrypto . I'll add pagination to the targets page this week. Regards

**Comment by santiagolizardo** [comment]
Just so that I can test it with your volume. What's the number of targets you are adding? I have tried adding 1000 and takes a few seconds (< 3s) to load but works fine (no hangs or rendering lags) 
I'll add pagination anyway because I think is necessary, but wondering if I should be testing with less or more based on your usage.
Thanks!

**Comment by 0xcrypto** [comment]
> Just so that I can test it with your volume. What's the number of targets you are adding? I have tried adding 1000 and takes a few seconds (< 3s) to load but works fine (no hangs or rendering lags)
> I'll add pagination anyway because I think is necessary, but wondering if I should be testing with less or more based on your usage.
> Thanks!

I did around 50k I think.

**Comment by santiagolizardo** [comment]
Hi @0xcrypto . I have pushed the changes to support pagination on the project targets view. Let me know if they look OK to you. Thanks

**Comment by 0xcrypto** [comment]
We already running reconmap in prod so will update later. Thanks for the update <3
