### ISSUE TITLE
Vulnerability tags

### ISSUE THREAD

**Issue by noraj** [reconmap/reconmap#53]
I saw there is the possibility to add tags to vulnerabilities.

![image](https://user-images.githubusercontent.com/16578570/129480375-b25a1ce5-f068-411e-91d9-92f71bdc058e.png)

There is also the `tags` fields on the JSON export.

But tags are not displayed on the vulnerability view, nor are in the vulnerability list of a project or the the global one, they are not taking into account for the search either.

![image](https://user-images.githubusercontent.com/16578570/129480416-25669047-af11-4ec2-9a23-e7f313a13c57.png)

So there are tags but I don't see them used anywhere.

**Comment by santiagolizardo** [comment]
Hi @noraj ; You might be running an old version of the web client. On recent versions the tags are displayed on the vulnerability list page, and on the vulnerability details page as well.

![image](https://user-images.githubusercontent.com/220190/129481147-a448c2ba-d374-4c52-beec-1135be6224d1.png)

![image](https://user-images.githubusercontent.com/220190/129481153-90ff497c-005c-4641-a5ad-5351abf37def.png)

For now they are mostly informational. They can show user added info or command related info. (eg the nmap tag is added to vulnerabilities found using the name command)

In the future we'll use this to show related info. Eg, a linux tag on target will be presented with a list of commands that can run on linux. This is just an example of many I can think of.

Regards

Regards

**Comment by noraj** [comment]
> Hi @noraj ; You might be running an old version of the web client. On recent versions the tags are displayed on the vulnerability list page, and on the vulnerability details page as well.

You are right, I missed them, they are indeed displayed.

> In the future we'll use this to show related info. Eg, a linux tag on target will be presented with a list of commands that can run on linux. This is just an example of many I can think of.

Cool idea. They could also be used for search as keywords, and maybe creating some tags index so when you click on the tag badge a list of all vulnerabilities with the same tag is displayed. So if columns on the vulnerability list could be sortable and filterable (like for categories in #49) it means we could be able to filter/sort the vulnerability list by tag and so the tags index would just have to be the vulnerability list with a tag filter per-applied.

**Comment by santiagolizardo** [comment]
I just pushed an update to make all tags clickable. When you click on a tag, it goes to the search page and shows results for commands or vulnerabilities matching that tag.
Thanks!

**Comment by noraj** [comment]
Amazing as always. It works well.
