### ISSUE TITLE
Vulnerability template

### ISSUE THREAD

**Issue by noraj** [reconmap/reconmap#54]
Right now a vulnerability template is just a vulnerability where `is_template = 1` has been set.

But there are a bunch of values / fields that are useless for templates that are still present and some are even required.

```json
      "status": "open",
      "substatus": "reported",
      "project_id": null,
      "project_name": null,
      "target_id": null,
      "target_name": null,
      "target_kind": null,
```

I guess (I have not verified) it's because vulnerability templates are stored in teh same SQL table as the vulnerabilities and so they are forced to have the same schema?

**Comment by santiagolizardo** [comment]
You are right @noraj . They are all stored on the same table. But I see how carrying that information on templates is a waste. I'll create a view of the mysql table just for templates that returns only what a template needs. Thanks for pointing this out 👍🏼

**Comment by noraj** [comment]
unstale

**Comment by santiagolizardo** [comment]
This has now been resolved. If you export vulnerability templates you won't get things that are only applicable to vulnerabilities. Thanks!

**Comment by noraj** [comment]
I just tested, it works flawlessly.
