### ISSUE TITLE
Feature addition - Add ability to define and edit tasks in project template

### ISSUE THREAD

**Issue by racoon-city** [reconmap/reconmap#62]
Hello, 

First of all, great work on this tool, it is impressive how it has been developed and how many features now it has, please keep the amazing stuff, all your community greatly appreciates the efforts!.

As the title implies and as we (a team) are currently using the tool considerably, we would like to know if it might be possible to define and edit tasks in project template. Currently, tasks are created via the "Tasks" entry and can be assigned to existing projects only,

Here I attach a simple screenshot for clarification
![unnamed (1)](https://user-images.githubusercontent.com/89659747/131171649-7d7326a6-e53c-4024-ac34-211376c10c90.png)

Thank you very much!,

**Comment by santiagolizardo** [comment]
This has now been done and pushed to the demo server in case you want to have a look. Thanks!
