### ISSUE TITLE
Error when deleting multiple vulnerabilities

### ISSUE THREAD

**Issue by Ned-Flanders** [reconmap/reconmap#65]
When I tick the box next to some vulnerabilities and hit delete, I get a 500 internal server error

Console says

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/vulnerabilities. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
TypeError: NetworkError when attempting to fetch resource.
Uncaught SyntaxError: function statement requires a name

**Comment by santiagolizardo** [comment]
Hi @Ned-Flanders ; I couldn't reproduce this error. Are you still seeing it?

**Comment by Ned-Flanders** [comment]
Hi @santiagolizardo I am still having this issue and I'm not sure why

I have pulled the latest changes with the following command

docker-compose stop
docker-compose pull
docker-compose rm -v
rm -rf data-mysql
docker-compose up -d

It seems to work on the demo but I'm not sure why it errors for me

**Comment by Ned-Flanders** [comment]
Hi @santiagolizardo apologies for the delay responding, I hadn't seen your reply. I believe the issue is with my local version, from the JS errors I'm getting the following when trying to delete via the checkbox.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/vulnerabilities. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

NetworkError when attempting to fetch resource.
api.js:36

TypeError: NetworkError when attempting to fetch resource.
onClick List.js:76
