### ISSUE TITLE
Filtering on vulnerabilities pages

### ISSUE THREAD

**Issue by Ned-Flanders** [reconmap/reconmap#66]
It would be good if we had filtering options on the vulnerability pages, so we can hide/show vulnerabilities, look for a specific host, filter by CVSS score, status, risk etc.

**Comment by Ned-Flanders** [comment]
Duplicate suggestion of

**Comment by santiagolizardo** [comment]
Hi @Ned-Flanders ; Just FYI; I have added some filters to the vulnerabilities page. More to come. Thanks!
