### ISSUE TITLE
Checkbox for select all on that page

### ISSUE THREAD

**Issue by Ned-Flanders** [reconmap/reconmap#67]
If we had a checkbox which allowed us to select all the vulnerabilities on the page, and then set the status of multiple vulnerabilities rather than selecting them one by one

**Comment by santiagolizardo** [comment]
I just added a checkbox on the table header that does this for the vulnerabilities table. Cheers

![image](https://user-images.githubusercontent.com/220190/135349393-a770c93b-e108-478c-bb73-67988d1fb084.png)

**Comment by Ned-Flanders** [comment]
Awesome, thank you!

**Comment by Ned-Flanders** [comment]
Sorry I was just going over this feature request, would it be possible to have a dropdown next to the "Add vulnerability" and "Delete selected" where we could set the status of multiple vulns, for example assigning "Closed (Remediated)" using the checkbox function?
