### ISSUE TITLE
Widget for new vulns

### ISSUE THREAD

**Issue by Ned-Flanders** [reconmap/reconmap#72]
Would it be possible to add a widget on the dashboard just for new vulns? This would be good for setting up the API to pull new scan results in and being able to see any vulns which have the status "Open (Reported). Then we would be able to see any news vulns which have been discovered by scans.

**Comment by santiagolizardo** [comment]
![image](https://user-images.githubusercontent.com/220190/144817031-9444529a-6083-4afa-9057-75c51da1e6a8.png)

Done! Thanks for suggesting this feature.
