### ISSUE TITLE
OpenVAS XML import

### ISSUE THREAD

**Issue by pixelsquared** [reconmap/reconmap#76]
I am looking for a way to import OpenVAS XML reports.

**Comment by pixelsquared** [comment]
Example report of a windows 10 system scan
[report-156e8e9a-7c65-413d-beb0-9aa02d605736.zip](https://github.com/reconmap/reconmap/files/7707308/report-156e8e9a-7c65-413d-beb0-9aa02d605736.zip)

**Comment by pixelsquared** [comment]
Example report of a windows XP scan
[winxp scan.zip](https://github.com/reconmap/reconmap/files/7707609/winxp.scan.zip)

**Comment by santiagolizardo** [comment]
Hi @pixelsquared ! Thanks for opening this ticket. I have updated openvas support with your test cases. (https://github.com/reconmap/php-command-output-parsers/commit/b2449e643844074ba9957936a1c84d86bbcaa72b)

Let me know if everything is working well with you on that. Thanks

**Comment by pixelsquared** [comment]
@santiagolizardo When will this feature be available in the docker images?

**Comment by santiagolizardo** [comment]
Hi @pixelsquared ; That's in the docker images as well. The Docker images as built automatically on every push to master so typically you get them the same day of the change. Thanks
