### ISSUE TITLE
Better filters for vulnerabilities page and bulk edit

### ISSUE THREAD

**Issue by pixelsquared** [reconmap/reconmap#77]
I am looking for the ability to filter vulnerabilities on data like: status, risk, category, project, etc.

In addition the ability to bulk edit the filtered results.

**Comment by santiagolizardo** [comment]
Hi @pixelsquared ! 
I am working on this filtering now. I'll add a bunch of dropdowns to filter but I am also planning to introduce a query language that would be much more versatile. Something along these lines: `status = open AND risk IN (medium, high)`
