### ISSUE TITLE
Idea: use GrapesJS to build reports

### ISSUE THREAD

**Issue by pixelsquared** [reconmap/reconmap#80]
https://grapesjs.com/

This idea may be too complex but I think I would be awesome to use something like GrapesJS to easily build reports. GrapesJS might not be the right tool for this but hopefully you see what I am thinking.

**Comment by santiagolizardo** [comment]
Thanks for opening this ticket @pixelsquared . Out of curiosity, why do you think GrapeJS is better/easier than just editing Word templates?
An improvement to the reporting system is overdue but I am not convinced GrapeJS is the replacement yet.

**Comment by pixelsquared** [comment]
GrapeJS maybe too complex and not quite right. 
I thinking about a block based editor because I think it is easier to visually see what is happening especially if you see it with data in it with live preview of the output.. And more complex reports that are hard build with templating in word like with charts and graphics.
